# Generated by Django 2.2.28 on 2024-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sendfrom', models.CharField(max_length=50)),
                ('sendto', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oid', models.CharField(max_length=50)),
                ('t_name', models.CharField(max_length=50)),
                ('start_station', models.CharField(max_length=50)),
                ('end_station', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('go_day', models.DateField()),
                ('seat_id', models.CharField(max_length=50)),
                ('seat_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('username', models.CharField(max_length=50)),
                ('u_carid', models.CharField(max_length=50)),
                ('buy_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-buy_time'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_login', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'session',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station', models.CharField(max_length=50)),
                ('en_station', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=50, unique=True)),
                ('start_station', models.CharField(max_length=50)),
                ('end_station', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time', models.TimeField()),
                ('c_seat', models.IntegerField(max_length=10)),
                ('c_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('b_seat', models.IntegerField(max_length=10)),
                ('b_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_seat', models.IntegerField(max_length=10)),
                ('a_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(max_length=50)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['id'],
            },
        ),
    ]
